### ISSUE TITLE
Symbol’s function definition is void: always

### ISSUE THREAD

**Issue by my-little-repository** [enricoflor/math-tex-convert#1]
I downloaded math-tex-convert using Melpa with emacs 27.1, This is version: 20220912.313 of the package. The package did not autoload so I put `(require 'math-tex-convert)` in my init file in order to load it.

I tried the function `math-tex-convert-to-unicode` on the line 

      $\alpha+\beta$

and got the error 

    math-tex-convert--replace: Symbol’s function definition is void: always

and indeed I don't see where such function is defined.

**Comment by enricoflor** [comment]
Mmm this is a bit strange, because for me `always` is defined in `subr.el` since Emacs version 1.1. In any case, since all it does is return `t`, I replaced it with a lambda expression in 91a9588f0d2d145f1695a531cc8bba8ec0adee3b . I also put autoload cookies on the two command definition in that commit. The new version should be on Melpa as soon as the next rebuild is complete, let me know if that works for you!

**Comment by my-little-repository** [comment]
Yes, it works. 

The `always` function was defined on February 2021 in this commit https://github.com/emacs-mirror/emacs/commit/825aed11d267f7879ca8915eb2b0d154e0beb2d4 and is not part of emacs 27.1 which was released on August 10, 2020.

Thanks for your help.
